# Generated by Django 5.2.5 on 2025-08-28 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primera_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Lector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('rut', models.CharField(max_length=10)),
                ('digito_verificador', models.CharField(max_length=1)),
                ('correo', models.CharField(max_length=30, null=True)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=60)),
                ('id_biblioteca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primera_app.biblioteca')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=15)),
                ('titulo', models.CharField(max_length=40)),
                ('paginas', models.CharField(max_length=700)),
                ('copias', models.CharField(max_length=100)),
                ('id_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primera_app.autor')),
                ('id_biblioteca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primera_app.biblioteca')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_lector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primera_app.lector')),
                ('id_libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primera_app.libro')),
            ],
        ),
    ]
